travis:
  secure:
    BINSTAR_TOKEN: gkItuIjVCBbK/u7S3rIEuKJdnT8nwA1W32oRrBELOqAB9+/fNtlCwdzxO/OKNloHYl3x/thpfnFnTL7jmCkhM3CGe9dFbzQP1PLzQOxVXz8B5iPd8VPbLgcb+EBUIGn9NPATzFFs7lM65OC36FewgZ1dImD+2vZbxeHikq9vrQVrwpOMnFy/9jO3kt5QWpJRMJwRrQec82WBJqJ4d/+YqqUh9D590kSd1y+7nVxOoSvr8+flPPuq6a9w5P6gfZSmal87uh6G6BAdvD067fK173GpptfEgwdKw2RHj+zwBN+FUGUCgEk54y/FD1FhUYpr5/1/Dur5wefSOvkYXKGohO7DnqZu6efxurVrRg+t6SvFwUXI/5ybPOLPa0VltslMs8BvkY4Y1V1Lt/WDp2JIEufRkjcwwFAX5v7rf/ZZ/3os2ahnl05yvtFR3JRbyljpKVf0ZiF5/CrxXg85jUMX/5b7xBnUAozyGmeVNViTHCXfFpnSTFM9RxpArw2FhhxWdSVtQSZJHryRw9+o5sjpt1EYsR7ZoLUQMiEdeMYn6QYI/4xjd6DgMPUwHmjQIUUzSYJu7bs08gL9R5CnjpLZfi0aE95wMD3m5HtqXFskWSKQvqLeb7nvv2uRNt7gfxvJ1zZnAkT0QLu2GxS4XIMj7Az9b5VafUToa+4SyXdbjkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
