travis:
  secure:
    BINSTAR_TOKEN: wwYiA1Mq3lDViXKs+ZJLJwe+luRXFHespUdn2CZ3fKylDC0k53SErGuTDQ7dTgXa+lvpPHThigYj0HkA0al5y2ou6gG8P5ffmXlgUPqAFDrzucr7CIZDLHIqDa9/ztDg4Gd6P5jPZBezRPPGqr8uZ+PJT8XjlEaapz9vP9JGp9EhXYC2Lq8RkfEBJR6i5W+JGZ61SXJ20tKWIlQ+ZP3IRFiLPitacDkAUeqBJVLcvlZlqo+r16+gCZm2kgGyg6c9mCzGyibghVsux7veTjpPM2oyNJReTDqaLPlMQKtJ6DLBkHz8jgFxMru8i78/02576AziuX6jLEHLrYUzlaJfO1pNzqBhhGQ/OOp79lSgyIaccWU39hvnpdbtYFowTLzPeNFikdLu3EQxFyIsgSHvyn2tg8EjW/0ScNO875kMr/Mh4HthyJj9YCsvpvV5oSbRvo7f1CdK/kKG/sxYoprKwJcBXFDel0zzwkk/aFJi7KH71xDv1URQrllWSs9c6lof8KtKLMN2FQRgWucfXIoba2Q0EuaRVUW7O5ExjjXa9nnCSpsjgu6AdUCl8mUv+uSBbf/0aN1vKwE3cuxdU8iK5eylqK/6jfBgb6eLKmoZRdg8G0jARgeQ9mR/biXxJ8JH+JySo1mLfvZu/+JQrJO0Mjq6x4GSvaGI9BTcE3HENLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
