travis:
  secure:
    BINSTAR_TOKEN: LMR9vYziVkUYzVEJp+jGO27fA8uvApCUbsVqK2Ib7/tyxnZ3XVmOEMYDxBGtUZR70D8azf+kc3LBMqpZJBXl3lJYi5CKTKEE+FihgoboVvDChQYwVZzKhUx8QaJLDGwAG6WIs0n0B6T7kGwifoJH3FVTtVWmsDp3tYsTBL4qakcKGQ/b7KVc69sfCyLIEvzwH35et/eRUBoatD7YZS0IReq8DdYNNLxnWHWP+YiKnecLVrkL1FofZYoLCsMbu8oL/jCrAXeGRQ/B3X9fIiesgWXhfUMvOo/8ec2r714Sc00tKxaIPNIRF1zmLeDgspw0Nv5oem42x4gF8eX8MJi1qc0h+ripDpJbirdGFEqYMWu8vHeTWm6SfwlyYzkHzT2Yf8Sh9tfHIAWtu6YDBDKkqO88dJLr//Q5Wxxl7+kQCV1mQI0MP3oQ51PRqPOreNdxpgypEZY+rwWpHD9/sGQD1RDz+z0T+vYdv7MbDyT28as9bz/aujrJIpkwOvhgRIuIm4ldz+LTvilsDK9yx+QoEzDCnep8vHbwNQRyqoW6Wcnqohtyrw7yN+aqTDvXjyBE6agdB2tVDhFJCoWGcWuKZQnwfBbwwCwyBxNM0zfqUhc/TvsZt26oClBejc1KsV0FkEMm/rZuaCizk0wYsAQ4bnoY5EzPpnZxdIgt5YJL+gM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
