appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XS11IyrfRB93vd9Zefv0jVNKvYuWXblS0B9Blvpa/0ljl30RCvu07daF6NpciT8nXjqbRxzWW/FOLuPgCP9NY4jc3ywChxdWZ1weQMJO3S9SxKD3lelPUtqZezvin3w4i9e8uLVBB9sFTsK6RpyhOOZHxXyFOXXDlTaWJW8qFAc8NB3uNss8v7hsF1bExXMxEck3nBjXz5pYwBXDxUizYbizW8kO3EK7YUjgoCXuuUXL42HkVqRa87f+UhtTilMVx1YMpjH5QlDW6H4yUYTsC41mDw2q8cesnt7BTsslU50Ahi54gsewyjCB1ODEPxGEOlHv4ou9T5jgP6kAd1rYjByMio7Z/rCfmJiuIadW7Mz+iM6O06awroUCs31lgxldUvC5cA6pQyAlbI6yD0iyowPxGGUw+iBfpshNOqzse76JomjR1W3z/oNLWH/ufF3lC58HLCqAeS7v8dLbV8jYIDdxIOcdj1uuUMu2o1nroNzaQ+6orUWtWHJe+GYCpCDLiwjlBnbQsKdyKg1CW7ObT8Z/JEyx/46y0bF/q0BVsLwvYOQog8sHvdTByWo04Gp3IiCcCjUc7y8FzzguPy2B17fW4n2I2I5aOAWzPRMhtcGfYOf5x4+1s/ilFQawD0I2Khm+D+y2aqZc4T4ddyYPkekPu7QbH3RJzxaMhM0xcM0=}
